HW04 is completed
vordzer/golang_prof pull request #4
Opened 2023-05-20 12:43 UTC by vordzer

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-05-22 10:33 UTC, ityulkanov requested changes
Отличное решение с чистым кодом, но пока принять не могу, оставил комментарий.

2023-05-22 10:33 UTC, ityulkanov commented on hw04_lru_cache/list.go
> +
Принять не смогу, т.к. этот метод условию задачи не соостветствует. Тут o(n) вместо o(1). 
Подсказка: вы можете модифицировать код из темплейта задачи, к примеру изменять структуру ListItem.

2023-05-24 19:41 UTC, ityulkanov approved these changes
Аппрувнул, т.к. формально условия задачи выполнены. Но пару комментариев оставил :)

2023-05-24 19:41 UTC, engineer-go commented on hw04_lru_cache/list.go
> +		back:  nil,
имхо это излишне. Т.к. по умолчанию эти значения именно такими и будут

2023-05-24 19:41 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +	keys     map[*ListItem]Key
Тоже вариант. Но я немного другое решение предлагал всё же. Тут мы вынуждены будем следить что удаляем из обеих мап значения, это усложняет код, что приводит к ошибкам. Ключ можно писать в сам ListItem.Value и если нужно удаление то забирать оттуда через приведение типов нужный ключ.

2023-05-25 09:15 UTC, vordzer commented on hw04_lru_cache/list.go
> +		back:  nil,
Удалил лишние инициализации. Плюсовая привычка всегда это делать)

2023-05-25 09:16 UTC, vordzer commented on hw04_lru_cache/cache.go
> +	keys     map[*ListItem]Key
Убрал map keys. Сделал так, как я понял совет писать в listItem. Насколько я понимаю, это всё должно оставаться на уровне cahe.go, не хотелось бы изменять в list.go что-то для решения проблемы cache.

2023-05-25 10:45 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +	keys     map[*ListItem]Key
Да, приблизительно такое решение я в основном и вижу. Согласен, что излишних модификаций лучше избегать, если такая возможность есть.

2023-05-29 07:20 UTC, merged